services:
  backend:
    image: ghcr.io/hossamvahid/partyhelper/party-helperbe:latest 
    ports:
      - "3278:8080"
    environment:
      - DATABASE=Host=db;Port=5432;Username=postgres;Password=1234;Database=app_db
      - ASPNETCORE_HTTP_PORTS=8080
      - KEY=PutAnKeyHere
      - ADMIN_EMAIL=admin@admin.com
      - ADMIN_PASSWORD=admin
      - ISSUER=localhost
      - AUDIENCE=localhost
    depends_on:
      - db
    networks:
      - backend_network

   
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
    ports:
      - "5434:5432"
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge
