// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using party_helperbe;

#nullable disable

namespace party_helperbe.Migrations
{
    [DbContext(typeof(PgSQLDbContext))]
    [Migration("20241202185841_PartyHelper")]
    partial class PartyHelper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("party_helperbe.DataAccess.Models.Member", b =>
                {
                    b.Property<int>("memberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("memberId"));

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<string>("emailAddress")
                        .HasColumnType("text");

                    b.Property<string>("userName")
                        .HasColumnType("text");

                    b.HasKey("memberId");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("party_helperbe.DataAccess.Models.Participant", b =>
                {
                    b.Property<int>("participantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("participantId"));

                    b.Property<int?>("memberId")
                        .HasColumnType("integer");

                    b.Property<string>("participantName")
                        .HasColumnType("text");

                    b.Property<int?>("partyId")
                        .HasColumnType("integer");

                    b.HasKey("participantId");

                    b.ToTable("Participants");
                });

            modelBuilder.Entity("party_helperbe.DataAccess.Models.Party", b =>
                {
                    b.Property<int>("partyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("partyId"));

                    b.Property<int>("creatorId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("partyDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("partyName")
                        .HasColumnType("text");

                    b.HasKey("partyId");

                    b.ToTable("Partys");
                });
#pragma warning restore 612, 618
        }
    }
}
